### ISSUE TITLE
Why is this repository empty? Where can I find the services mentioned in the readme.md?

### ISSUE THREAD

**Issue by Sathyaish** [NuGet/ServerCommon#1]
The readme file for this repository mentions that it has common services such as logging, configuration and the NuGet keyvalut. But the source is empty. Where do I find these services?

**Comment by xavierdecoster** [comment]
These are still in the `develop` branch. We'll merge to master when we have a v1.0.0 consumed by our services.

**Comment by Sathyaish** [comment]
Thank you.
